CREATE INDEX IF NOT EXISTS idx_agency_staff_agency_id ON agency_staff(agency_id);
CREATE INDEX IF NOT EXISTS idx_agency_staff_user_id ON agency_staff(user_id);
CREATE INDEX IF NOT EXISTS idx_clients_agency_id ON clients(agency_id);
CREATE INDEX IF NOT EXISTS idx_clients_user_id ON clients(user_id);
CREATE INDEX IF NOT EXISTS idx_account_code_mappings_agency_id ON account_code_mappings(agency_id);
CREATE INDEX IF NOT EXISTS idx_receipts_client_id ON receipts(client_id);
CREATE INDEX IF NOT EXISTS idx_receipts_agency_id ON receipts(agency_id);
CREATE INDEX IF NOT EXISTS idx_receipts_status ON receipts(status);
CREATE INDEX IF NOT EXISTS idx_receipts_date ON receipts(date DESC);
CREATE INDEX IF NOT EXISTS idx_receipts_reviewed_by ON receipts(reviewed_by);